### ISSUE TITLE
Problem with qwt_system_clock.h

### ISSUE THREAD

**Issue by leo-bart** [mbsim-env/hdf5serie#5]
When compiling h5plotseries from source, I get the following error when running `configure`:
```
checking for qwt_system_clock.h... no
configure: error: Can not find qwt_system_clock.h! Maybe a qwt5 header is used!
```
So I added the `--with-qwt-inc-prefix=/usr/include/qwt` to config (that's where my `qwt_system_clock.h` is) and the issue changed to
```
checking for qwt_system_clock.h... yes
configure: error: Can not link with qwt >= 6
```

I understood why the first error appeared (no file found). But the second one is a mystery to me: isn't `qwt_system_clock.h` supposed to belong to qwt6?

There is also a contradiction on `README`: `Another requirement is libqwt6. The program will not work with libqwt6.` Shouldn't it say `The program will not work *without* libqwt6?`

**Comment by leo-bart** [comment]
Tried to comment out the following section of the `configure` script:
```
if ac_fn_cxx_try_link "$LINENO"; then :

else
  as_fn_error $? "Can not link with qwt >= 6" "$LINENO" 5
fi
```

In this case, `configure` runs ok, `make` builds everything, but I get the following error when linking:
```
make[2]: Entering directory '/home/leonardo/Software/mbsim-env-build/hdf5serie/h5plotserie/h5plotserie'
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgtk2.so', needed by 'all-am'.  Stop.
```

**Comment by friedrichatgc** [comment]
h5plotseries needs qwt6 for qt5 (qwt5 is NOT working). I will adapt the wrong messages. The installation path of the qwt5 headers and the library files as well as the name of the library files highly differs from Linux distribution to Linux distribution. qwt6 also does not provide e.g. a pkg-config file which can be used to automatically detect these path and names.

Per default h5plotserie search the qwt headers/libraries in the system default dirs where as library name libqwt.so* is used.
If the header qwt_system_clock.h is installed in /dir1/dir2/qwt_system_clock.h you need to pass --with-qwt-inc-prefix=/dir1/dir2 to configure.
If the library file is named/placed in /dir2/dir3/libqwt6qt5.so you need also to pass --with-qwt-lib-prefix=/dir2/dir3 --with-qwt-lib-name=qwt6qt5 to configure.
Note that as --with-qwt-lib-name you need the pass the library basename being the filename excluding the "lib" prefix and excluding the ".so*" postfix.

I will also try to improve the error messages.

**Comment by leo-bart** [comment]
`--with-qwt-lib-name=qwt-qt5` was essential in my case, thank you.

The build error, however, persisted. I'm using Ubuntu 20.04 and the Qt5 theme libraries were not installed, so I had to add them by using
```
sudo apt install qt5-style-plugins 
```
but now `libbb10styleplugin.so` is missing and is apparently not present on recent distributions. I'm still trying to find out how to get it.
